PRINT_FREQ: 10
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/mobilenet_v3_large_hardswish_c5_cosine_cccf_224_b256_e90_g4'
RESUME: "outputs/mobilenet_v3_large_hardswish_c5_cccf_224_b256_e90_g4/model_best.pth.tar"
TRAIN:
  EVAL_EPOCH: 1
  START_EPOCH: 1
  MAX_EPOCH: 90
  TOP_K: (1, 3, 5, 10)
  CALCULATE_ACCURACY: True
METRIC:
  MAX_CATE_NUM: 10
  FEAT_TYPE: 'hardswish'
  AGGREGATE_TYPE: 'identity'
  ENHANCE_TYPE: 'identity'
  DISTANCE_TYPE: 'cosine'
  RANK_TYPE: 'normal'
DATALOADER:
  TRAIN_BATCH_SIZE: 256
  TEST_BATCH_SIZE: 256
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  COLLATE_FN: 'default'
DATASET:
  NAME: 'CCCF'
  TRAIN_ROOT: './data/cccf'
  TEST_ROOT: './data/cccf'
TRANSFORM:
  TRAIN_METHODS: ('RandomResizedCrop', 'RandomHorizontalFlip', 'RandAugment', 'ToTensor', 'RandomErasing')
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor')
  TRAIN_RESIZE_CROP: (224,)
  RandomErasing: (0.5, (0.02, 0.33), (0.3, 3.3), 0, False)
  TEST_RESIZE: (256,)
  TEST_CROP: (224,)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), False)
MODEL:
  ARCH: 'mobilenet_v3_large'
  PRETRAINED: True
  NUM_CLASSES: 502
  SYNC_BN: False
  CRITERION:
    NAME: 'cross_entropy_loss'
    REDUCTION: 'mean'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-1
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'multi_step_lr'
  IS_WARMUP: True
  WARMUP_EPOCH: 5
  MULTISTEP_LR:
    MILESTONES: [ 30, 60, 80 ]
    GAMMA: 0.1