PRINT_FREQ: 10
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/mobilenet_v3_large_linear_c20_cosine_cccf_224_b256'
RESUME: "outputs/mobilenet_v3_large_hardswish_c5_cccf_224_b256_e90_g4/model_best.pth.tar"
TRAIN:
  TOP_K: (1, 3, 5, 10)
EVAL:
  FEATURE:
    FEAT_TYPE: 'linear'
    AGGREGATE_TYPE: 'IDENTITY'
    ENHANCE_TYPE: 'IDENTITY'
  INDEX:
    DISTANCE_TYPE: 'COSINE'
    RANK_TYPE: 'NORMAL'
    RE_RANK_TYPE: 'IDENTITY'
    GALLERY_DIR: ''
    MAX_CATE_NUM: 20
    MODE: 0
  METRIC:
    EVAL_TYPE: 'ACCURACY'
DATALOADER:
  TEST_BATCH_SIZE: 256
  COLLATE_FN: 'default'
DATASET:
  NAME: 'CCCF'
  TRAIN_ROOT: './data/cccf'
  TEST_ROOT: './data/cccf'
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor')
  TEST_RESIZE: (256,)
  TEST_CROP: (224,)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), False, 1.0)
MODEL:
  ARCH: 'mobilenet_v3_large'
  PRETRAINED: True
  NUM_CLASSES: 502
  SYNC_BN: False
  CRITERION:
    NAME: 'cross_entropy_loss'
    REDUCTION: 'mean'